version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    # restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=productdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    # restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    links: # <-- add this
      - postgres # <-- add this
  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   ports:
  #     - 27017:27017

volumes:
  postgres: