version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    # restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=productdb
      # - PGDATA=/var/lib/postgresql/data/pgdata
      - PGDATA=/temp
    volumes:
      # - postgres:/var/lib/postgresql/data
      - ./postgres/data:/var/lib/postgresql/data

    ports:
      - 5432:5432
######################################################
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    # restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    links: # <-- add this
      - postgres # <-- add this
    volumes:
      - ./pgadmin4/data:/var/lib/pgadmin
######################################################
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=orderdb
    ports:
      - 27017:27017
    volumes: 
      - ./mongoDB/data:/data/db
######################################################
# database url connection:
#   mongodb://127.0.0.1:27017/orderdb
######################################################

  mongoclient: 
    image: mongoclient/mongoclient
    container_name: mongoclient
    hostname: mongoclient
    ports:
      - 3500:3000
    volumes: 
      - ./mongoClient/data:/data/db mongoclient/mongoclient
    depends_on:
      - mongodb
    links: # <-- add this
      - mongodb # <-- add this

# volumes:
#   postgres: